### PR TITLE
Install cdms kernels

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
@bloer, do you think this is fine?

**Comment by bloer** [comment]
Seems reasonable.  I guess the users' home areas are non-volatile, so they only have to do this periodically, not every time they spin up an image?  

I wonder if the script should maybe take an argument an only install the latest N.  If we keep pusing new releases the users' environment will quickly get cluttered with lots of kernels.

**Comment by zonca** [comment]
yes correct,

I think it would be nice if we can delete user kernels that are not available anymore on cvmfs. however we have to devise a trick to identify them properly and be sure we do not accidentally delete kernels created by the users.

**Comment by bloer** [comment]
Ideally once things stabilize, we won't ever delete things from CVMFS to fully preserve the ability to reconstruct historical analyses.  We'll see how long that lasts...

As for not deleting user kernels, I think telling them 
don't name your kernel `CDMS V[0-9][0-9]-[0-9][0-9]-[0-9][0-9]\(-RC[0-9]+)?`" 
is easy enough to follow

**Comment by zonca** [comment]
ok, thanks for your feedback!
I think our concerns seem not too worrisome, so I will keep it simple as it is right now and then we will adjust based on user feedback.

**Pull request merged**
